#!/usr/bin/env bash


CALL CSVWRITE('/Users/thomasbigger/Desktop/attractions_weather.csv', 'SELECT ID,SYGIC_TRAVEL_ID,RATING,LATITUDE,LONGITUDE,NAME,MARKER,PEREX,THUMBNAIL_URL,CATEGORIES,DS_SUMMARY,DS_ICON,DS_APPARENT_TEMPERATURE_HIGH  	DS_APPARENT_TEMPERATURE_LOW,DS_DEW_POINT,DS_HUMIDITY,DS_PRESSURE,DS_WIND_SPEED,DS_WIND_GUST,DS_CLOUD_COVER,DS_VISIBILITY  FROM ATTRACTION ', 'charset=UTF-8 fieldSeparator=; fieldDelimiter=');
